### ISSUE TITLE
Move from sliding tags to branch based versioning

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/git-tag-annotation-action#264]
# Project Initiative

Update the versioning strategy from a sliding tag[^1] to a branch-based release strategy. Per the references, updating the commit that a tag points to is not "the git way". Using a branch for a continuously updating point of reference in the repository is more natural, and supported by GitHub Actions.

### Sliding v2 branch

Have a branch called `v2` that points to some commit on the `main` branch, as suggested in the changes proposed in [2].

Example, going from:

```mermaid
gitGraph
  commit id: "fa6b1f8"
  commit id: "ca2f706" tag: "v2.0.1"
  commit id: "50860d3"
  commit id: "f164e28"
  commit id: "c2b9047 (v2)" type: HIGHLIGHT tag: "v2.1.0"
  commit id: "a473695"
  commit id: "fa3f790"
``` 

with the `v2` branch pointing to `c2b9047`, to

```mermaid
gitGraph
  commit id: "fa6b1f8"
  commit id: "ca2f706" tag: "v2.0.1"
  commit id: "50860d3"
  commit id: "f164e28"
  commit id: "c2b9047" tag: "v2.1.0"
  commit id: "a473695"
  commit id: "fa3f790 (v2)" type: HIGHLIGHT tag: "v2.1.1"
``` 

with the `v2` branch pointing to `fa3f790`.

### Dedicated v2 branch

Have a dedicated `v2` branch that `main` is occasionally merged into to cut a release. This is similar to the `main`-`develop` strategy (where `develop`=`main` and `main`=`v2`).

```mermaid
gitGraph
  commit id: "test" tag: "v2.0.1"
  branch v2
  commit id: "init branch"
  checkout main
  commit id: "feature"
  checkout v2
  merge main tag: "v2.1.0"
  checkout main
  commit id: "bugfix"
  checkout v2
  merge main tag: "v2.1.1"
  checkout main
  commit id: "chore"
```

### Rename `main` to `v2`

Stop using a `main` branch and just have `v2` branch. This would be simple, but means the `v2` ref is unstable. Hence, at the very list this would require a breaking change (i.e. jump to `v3`).

```mermaid
gitGraph
  branch v2
  checkout v2
  commit id: "fa6b1f8"
  commit id: "ca2f706" tag: "v2.0.1"
  commit id: "50860d3"
  commit id: "f164e28"
  commit id: "c2b9047" tag: "v2.1.0"
  commit id: "a473695"
```

### Others?

Suggestions are welcome (even if this issue has since been closed).

## References

1. https://git-scm.com/docs/git-tag#_on_re_tagging
1. https://github.com/actions/toolkit/pull/631 (and related)

[^1]: Sliding a tag meaning updating the commit that a tag points to.

**Comment by ericcornelissen** [comment]
At least initially, this project will go for the "**Sliding v2 branch**" approach.

### Progress

- [ ] Update the [Release Guidelines](https://github.com/ericcornelissen/git-tag-annotation-action/blob/c63fc13ac9d914f3d0779f61174b29e2c9e305d5/RELEASE.md)
- [ ] Update the [Release workflow](https://github.com/ericcornelissen/git-tag-annotation-action/blob/c63fc13ac9d914f3d0779f61174b29e2c9e305d5/.github/workflows/release.yml)
- [ ] Update the git refs (for v2)
- [ ] Update the git refs (for v1)
